# Generated by Django 3.2.9 on 2021-12-05 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='creador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='nombre',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='nombre',
            field=models.CharField(default='', max_length=200),
        ),
    ]
