# Generated by Django 3.2.9 on 2021-12-07 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211205_0830'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyecto',
            old_name='creador',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='tarea',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.proyecto'),
        ),
    ]
